# UI centralisée dans la Gateway
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.urls[0].name=AuthService
springdoc.swagger-ui.urls[0].url=/auth/v3/api-docs
#springdoc.swagger-ui.urls[1].name=User Service
#springdoc.swagger-ui.urls[1].url=/users/v3/api-docs
#springdoc.swagger-ui.urls[2].name=School Service
#springdoc.swagger-ui.urls[2].url=/schools/v3/api-docs

