server:
  port: 8081

spring:
  application:
    name: AuthService
  datasource:
    driver-class-name: org.postgresql.Driver
    username: auth_service
    password: auth_service#123@
    url: jdbc:postgresql://localhost:5432/authdb?createDatabaseIfNoExist=true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dariussteves44@gmail.com
    password: owva xtvy iedo iywm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379
#      password: redis_pass#123@

app:
  base-url: http://localhost:8081

jwt:
  secret: g6QXiyaSf2GYDpfAQydAa1TB8p00rXD2OWTiNQfieiVcOGfO2P7zLXwm37FYekBKDQtyICARczOlzXmKZO9roQ

